### ISSUE TITLE
Eliminate "Gearbox" and "Gear" from output

### ISSUE THREAD

**Issue by mikeschinkel** [gearboxworks/launch#3]
Anywhere there is _"Gear"_ we should remove it or use _"Container."_

For _"Gearbox"_ change to _"Launch"_ if it will make sense.

If something unclear, let's discuss.

![gear-terms](https://user-images.githubusercontent.com/153285/110259708-2267dd00-7f77-11eb-9d69-17abeb661534.jpg)

**Comment by MickMake** [comment]
DONE - Needs testing.

**Comment by MickMake** [comment]
Removed all refs.

**Comment by mikeschinkel** [comment]
Seems you missed some or added in some new ones:


![launch-start-imagemagick](https://user-images.githubusercontent.com/153285/113923959-2e81cd00-97b7-11eb-9801-9001edfd566c.jpg)
![launch-run-mountebank](https://user-images.githubusercontent.com/153285/113924136-730d6880-97b7-11eb-8843-abc01bd490ea.jpg)

**Comment by mikeschinkel** [comment]
![Cursor_and_-bash_and_Slack___GitHub___WPLib](https://user-images.githubusercontent.com/153285/117911058-1405ac80-b2ab-11eb-90d2-1ec452a1f508.png)

**Comment by mikeschinkel** [comment]
![gearbox](https://user-images.githubusercontent.com/153285/118097336-8c9a6500-b3a0-11eb-9955-f9eba7c5c7f3.png)

**Comment by mikeschinkel** [comment]
![](https://user-images.githubusercontent.com/153285/118097447-b489c880-b3a0-11eb-8024-ab1fcc56d8e7.png)
